name: 'Gradle Version Incrementer'
description: 'Automatically increments version in Gradle files with support for SNAPSHOT versions'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  file-path:
    description: 'Path to the gradle file'
    required: true
  increment-type:
    description: 'Type of version increment (major, minor, patch)'
    required: true
  mode:
    description: 'Action mode (update-file or comment-only)'
    required: true
    default: 'comment-only'
branding:
  icon: 'arrow-up'
  color: 'green'
runs:
  using: 'node16'
  main: 'dist/index.js'
