name: 'Gradle Version Incrementer'
description: 'Automatically increments version in build.gradle files and optionally commits changes'
inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  file-path:
    description: 'Path to the build.gradle file'
    required: true
    default: 'build.gradle'
  increment-type:
    description: 'Type of version increment (major, minor, patch)'
    required: true
    default: 'patch'
  mode:
    description: 'Operation mode (update-file or comment-only)'
    required: true
    default: 'comment-only'
outputs:
  previous-version:
    description: 'The previous version before incrementing'
  new-version:
    description: 'The new version after incrementing'
branding:
  icon: 'arrow-up'
  color: 'green'
runs:
  using: 'node16'
  main: 'dist/index.js'
