name: 'Gradle Version Incrementer'
description: 'Automatically increments version in Gradle files with support for SNAPSHOT versions'
inputs:
  file-path:
    description: 'Path to the gradle file containing version'
    required: false
    default: 'app/build.gradle'
  increment-type:
    description: 'Which version segment to increment (major, minor, patch)'
    required: false
    default: 'patch'
branding:
  icon: 'arrow-up'
  color: 'green'
runs:
  using: 'node16'
  main: 'dist/index.js'
